handled missing binary in script

diff --git a/morphoit b/morphoit
--- a/morphoit
+++ b/morphoit
@@ -3,11 +3,19 @@
 # exit on any subcommand failing, unset variables are errors
 set -eu
 
+# replace this with the name of the transpiler binary
+# in this case the BuildIt binary
+TRANSPILER_BIN=main
+
+TRANSPILER_BIN=$(realpath "$TRANSPILER_BIN")
+if ! [ -x "$TRANSPILER_BIN" ]; then 
+  >&2 echo "Could not find executable for partial evaluator binary ($TRANSPILER_BIN). Exiting."
+  exit 1
+fi
 if ! [ $# -eq 1 ]; then 
   >&2 echo "Usage: $(basename "$0") MORPHO_SRC_FILE_NAME"
   exit 1
 fi
-
 MORPHO_FILE_PATH=$1
 if ! [ -f "$MORPHO_FILE_PATH" ]; then
   >&2 echo "No such file '$MORPHO_FILE_PATH', exiting."
@@ -19,7 +27,7 @@ C_FILE_NAME="$FILENAME.c"
 BIN_FILE_NAME="$FILENAME.bin"
 
 # partial compilation to C file
-./main "$MORPHO_FILE_PATH" > "$C_FILE_NAME"
+"$TRANSPILER_BIN" "$MORPHO_FILE_PATH" > "$C_FILE_NAME"
 
 # compile C file to binary
 CFLAGS="-O3"
